import '@/styles/globals.css'
import { Header } from '@/widgets/header'
import type { Metadata } from 'next'

import Providers from './providers'

export const metadata: Metadata = {
  title: 'eggcoach',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
