import '@/styles/globals.css'
import { Header } from '@/widgets/header'
import type { Metadata } from 'next'
import Script from 'next/script'

import Providers from './providers'

export const metadata: Metadata = {
  title: 'eggcoach',
  description: 'Generated by create next app',
}

export const API = `//dapi.kakao.com/v2/maps/sdk.js?appkey=3571a2cdd7a0be20fa1175af24fef4ae&autoload=false`

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <Script src={API} strategy='beforeInteractive' />
      </head>
      <body>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
